plugins {
	id 'fabric-loom' version '1.10-SNAPSHOT'
	id 'maven-publish'
}

version = getSubprojectVersion(project)
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

dependencies {
	include(rootProject.project("banner-api"))
	include(rootProject.project("banner-transitive-access-wideners"))
	include(annotationProcessor("com.github.bawnorton.mixinsquared:mixinsquared-fabric:${property("mixin_squared_version")}"))
}

moduleDependencies(project, [
		"banner-api",
		"banner-transitive-access-wideners"
])