archivesBaseName = project.archives_base_name + "-api"
version = getSubprojectVersion(project)

moduleDependencies(project, [
        "banner-transitive-access-wideners"
])

processResources {
    duplicatesStrategy = DuplicatesStrategy.WARN
}

dependencies {
    include("net.minecraftforge:srgutils:0.4.13")
}